using ConferencePlanner.GraphQL.Data;
using HotChocolate.Execution.Configuration;

namespace ConferencePlanner.GraphQL;

public static class GraphQLServerConfiguration
{
    public static IRequestExecutorBuilder SetupApplicationGraphQLServer(this IRequestExecutorBuilder builder)
    {
        return builder
            .RegisterDbContext<ApplicationDbContext>()
            .AddAutoGeneratedTypes() // Auto-generation from HotChocolate.Analyzers package.  Name set in ModuleInfo else will be 'Add{ProjectName}Types()'.
            .AddGlobalObjectIdentification()
            .AddFiltering()
            .AddSorting()
            .AddInMemorySubscriptions();
    }
    
}